name = "expense-tracker-app"
type = "javascript"
main = "./api/expenses.js"
compatibility_date = "2023-10-20"

[[d1_databases]]
binding = "DB"
database_name = "f19179fd-6cc7-4f49-992c-e98f21b8f186>"
